const reviewOverviews = [
  'Um filme emocionante do início ao fim, com atuações incríveis e uma trilha sonora marcante.',
  'Decepcionante, a trama parecia promissora, mas acabou sendo previsível e sem graça.',
  'Uma obra-prima visualmente deslumbrante, mas a história deixa a desejar.',
  'Uma comédia leve e divertida, perfeita para uma noite descontraída.',
  'O roteiro é confuso e os personagens são rasos. Não recomendo.',
  'Uma história poderosa e tocante que ficará com você por muito tempo.',
  'Muito clichê, sem nenhuma inovação. Já vi filmes assim mil vezes.',
  'As atuações foram fantásticas, especialmente o protagonista que brilhou.',
  'Os efeitos especiais são bons, mas a história é fraca e sem profundidade.',
  'Um thriller eletrizante que te mantém na ponta da cadeira até o final.',
  'Filme lento e arrastado, difícil de manter o interesse até o fim.',
  'Cativante e emocional, um verdadeiro tributo ao poder da amizade.',
  'Nada original, parece uma cópia barata de outros sucessos.',
  'Excelente direção e uma narrativa envolvente. Altamente recomendado!',
  'Mal escrito e mal dirigido, uma verdadeira perda de tempo.',
  'Surpreendente e cheio de reviravoltas, um dos melhores do ano.',
  'Personagens sem carisma e uma história sem graça. Não gostei.',
  'Uma jornada emocionante com personagens complexos e bem desenvolvidos.',
  'Tedioso e sem energia, não consegui me conectar com a história.',
  'Uma aventura épica que te leva a um mundo de fantasia inesquecível.',
  'Diálogos forçados e um enredo previsível. Esperava mais.',
  'Um drama profundo e reflexivo que explora temas universais.',
  'Muito exagerado e cheio de clichês, não me convenceu.',
  'Uma experiência cinematográfica única, visualmente impressionante.',
  'Nada inovador, apenas uma repetição de fórmulas já conhecidas.',
  'Encantador e comovente, um filme que aquece o coração.',
  'Pouco empolgante e com um final decepcionante. Não recomendo.',
  'Uma mistura perfeita de ação e emoção, com uma história bem contada.',
  'Muito barulho por nada, o filme não consegue entregar o que promete.',
  'Um épico de tirar o fôlego, com atuações memoráveis.',
  'Raso e sem profundidade, não consegui me envolver com a história.',
  'Uma animação vibrante e colorida, perfeita para toda a família.',
  'Diálogos fracos e atuações medíocres, um filme facilmente esquecível.',
  'Uma história de amor encantadora que vai fazer você acreditar novamente.',
  'Nada empolgante, parecia mais um filme para TV do que para o cinema.',
  'Inspirador e bem executado, uma verdadeira joia cinematográfica.',
  'Trama incoerente e cheia de buracos, não vale o ingresso.',
  'Uma obra de arte com uma narrativa profunda e impactante.',
  'Clichê após clichê, sem nada de novo ou interessante.',
  'Cativante e emocionante, um filme que todos deveriam ver.',
  'Muito previsível e com personagens pouco desenvolvidos.',
  'Uma comédia romântica adorável e cheia de momentos hilários.',
  'Lento e chato, não consegui me conectar com a história ou personagens.',
  'Um filme que desafia expectativas e oferece algo realmente novo.',
  'Roteiro fraco e direção inconsistente, uma decepção.',
  'Uma aventura divertida e cheia de ação, ótima para toda a família.',
  'História rasa e previsível, esperava muito mais deste filme.',
  'Um thriller psicológico que te prende do início ao fim.',
  'Muito melodramático e forçado, não consegui levar a sério.',
  'Uma celebração da vida e da arte, um filme verdadeiramente inspirador.',
];

export default reviewOverviews;
